### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'sort'

### ISSUE THREAD

**Issue by stardust-96** [khufkens/align_images#1]
For following line of code in Colab:

!python /content/align_images/align_images.py -im1 rgb_image.jpg -im2 nir_image.jpg -m feature

I get this error:

Traceback (most recent call last):
  File "/content/align_images/align_images.py", line 195, in <module>
    aligned, warp_matrix = featureAlign(im1, im2)
  File "/content/align_images/align_images.py", line 127, in featureAlign
    matches.sort(key=lambda x: x.distance, reverse=False)
AttributeError: 'tuple' object has no attribute 'sort'

<img width="655" alt="image" src="https://user-images.githubusercontent.com/21253948/181461494-78d0552b-ac60-4191-8e05-d029c109319e.png">

**Comment by yuqizhi** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by yuqizhi** [comment]
添加 matches = list(matches)可解决
